NumPy:

1. Python Library
2. Scientific Computing
3. Framework to manage multi-dimensional arrays and matrices
4. Functions to perform operations on arrays

Ways to Represent NumPy arrays

1. np.array(): array of numbers
2. np.arange(): numbers in the specified range
3. np.linspace(): numbers in given range with specifed number of data points
4. np.logspace(): specified logarithmic numbers within the specifed range
5. np.zeros(): specified number of zeros
6. np.ones(): specified number of ones
7. np.identity(): specifed number of arrays with one of the sub-element unity
8. np.diag(): specifed elemnts are presented diagoally

In [1]:
import numpy as np

a = np.array([2,4,6,8])

In [3]:
a

array([2, 4, 6, 8])

In [2]:
b = np.arange(7)

In [3]:
b

array([0, 1, 2, 3, 4, 5, 6])

In [6]:
c= np.arange(2,6)

In [7]:
c

array([2, 3, 4, 5])

In [11]:
d = np.linspace(1,10,2)

In [12]:
d

array([ 1., 10.])

In [13]:
e = np.linspace(3,17,3)

In [14]:
e

array([ 3., 10., 17.])

In [15]:
f = np.logspace(1,5,2)

In [16]:
f

array([1.e+01, 1.e+05])

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
a1 = np.array([[2,4],[3,6],[4,8]])

In [22]:
a1

array([[2, 4],
       [3, 6],
       [4, 8]])

In [24]:
a1.ndim

2

In [26]:
a1.shape

(3, 2)

In [27]:
a1.itemsize

4

In [28]:
a1.dtype

dtype('int32')

In [29]:
a1.size

6

In [30]:
a1[1]

array([3, 6])

In [32]:
a1[0:2]

array([[2, 4],
       [3, 6]])

In [34]:
a1[:]

array([[2, 4],
       [3, 6],
       [4, 8]])

In [36]:
a2 = np.array([[1,2],[2,4],[3,6],[4,8]])

In [37]:
a2

array([[1, 2],
       [2, 4],
       [3, 6],
       [4, 8]])

In [38]:
a2.ndim

2

In [39]:
a3 = np.array([[1,2,3],[2,4,6],[3,6,9],[4,8,12]])

In [40]:
a3

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

In [41]:
a3.ndim

2

In [42]:
a3[:, :]

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

In [43]:
lst1 = [2,4,6,8,10]

In [45]:
lst1[1:3:2]

[4]

In [47]:
lst1[0:4:2]

[2, 6]

In [48]:
a3[1:3, :1] #Slicing- last elements are not included

array([[2],
       [3]])

In [2]:
#Modifying an array

import numpy as np

t1 = np.array([[2,4],[3,9],[4,16],[5,25]])

In [3]:
t1

array([[ 2,  4],
       [ 3,  9],
       [ 4, 16],
       [ 5, 25]])

In [4]:
t1[0,1] = 8

In [5]:
t1

array([[ 2,  8],
       [ 3,  9],
       [ 4, 16],
       [ 5, 25]])

In [6]:
#Iterate on the elements of 1-D array

arr = np.array([1,2,3,4])

In [7]:
arr

array([1, 2, 3, 4])

In [8]:
for x in arr:
    print(x)    #Iterates over each element of array in 1-D

1
2
3
4


In [11]:
arr2 = np.array([[1,2],[3,4],[5,6]])

In [12]:
for x in arr2:
    print(x)

[1 2]
[3 4]
[5 6]


In [13]:
for x in arr2:
    for y in x:
        print(y)

1
2
3
4
5
6


In [1]:
import numpy as np

In [2]:
a1 = np.array([4,6])
a2 = np.array([2,3])

In [3]:
print("Sum =", a1 + a2)
print("Diff =", a1 - a2)
print("Prod =", a1 * a2)
print("Div =", a1 / a2)

Sum = [6 9]
Diff = [2 3]
Prod = [ 8 18]
Div = [2. 2.]


In [5]:
#Array Manipulation
#Reshaping

a3 = np.arange(2,12,2)

In [6]:
a3

array([ 2,  4,  6,  8, 10])

In [7]:
a3.reshape(1,5)

array([[ 2,  4,  6,  8, 10]])

In [8]:
a3.reshape(5,1)

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10]])

In [9]:
a4 = np.arange(1,17)

In [10]:
a4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [11]:
a4.reshape(8,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [12]:
a4.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [13]:
a4.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [14]:
#Transposing Arrays

a5 = np.arange(1,9)

In [15]:
a5

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
a6= a5.transpose()

In [18]:
a6

array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
a7 = np.arange(2,13)

In [24]:
a7

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
#Flattening Arrays

d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [30]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
d.shape

(3, 3)

In [32]:
d.flatten()   #.flatten() gives you copy of array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
d.ravel()    #This gives a 'view' and changes the parent array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
#Combining Arrays

x = np.array([[2,4],[5,10],[7,14]])
x

array([[ 2,  4],
       [ 5, 10],
       [ 7, 14]])

In [45]:
y = np.array([[1,2],[3,4],[5,6]])
y

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
z = np.concatenate((x,y), axis = 0)

In [48]:
z

array([[ 2,  4],
       [ 5, 10],
       [ 7, 14],
       [ 1,  2],
       [ 3,  4],
       [ 5,  6]])

In [50]:
x1 = np.arange(1,9).reshape(4,2)
x1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [52]:
y1 = np.arange(2,12).reshape(2,5)
y1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [57]:
s1 = np.stack((x1,x1))
s1

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]],

       [[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [56]:
print("Shape =", s1.shape)

Shape = (2, 4, 2)
